FROM python
RUN pip install flask
COPY ./templates /home/myapp/templates
COPY mapquest-docker.py /home/myapp
CMD python3 /home/myapp/mapquest-docker.py
FROM python
RUN pip install flask
COPY ./templates /home/myapp/templates
COPY mapquest-docker.py /home/myapp
CMD python3 /home/myapp/mapquest-docker.py
FROM python
RUN pip install flask
COPY ./templates /home/myapp/templates
COPY mapquest-docker.py /home/myapp
CMD python3 /home/myapp/mapquest-docker.py
